import React, { useState } from 'react';
import { ThemeProvider } from '@mui/material/styles';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import theme from '../theme';
import Head from 'next/head'
import Layout from 'src/layout/Layout';


type appProps = {
  Component: any;
  pageProps: any;
};

export default function App(props: appProps) {
  const { Component, pageProps } = props;
  const [queryClient] = useState(() => new QueryClient());

  return (
    <React.Fragment>
      <Head>
        <title>App Logger</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <QueryClientProvider client={queryClient}>
        <ThemeProvider theme={theme}>
          <Layout mainPage={<Component {...pageProps} />} />
        </ThemeProvider>
      </QueryClientProvider>
    </React.Fragment>
  )
}
